### ISSUE TITLE
Session Metrics incorrect using hazelcast-jetty-sessionmanager

### ISSUE THREAD

**Issue by yogeshrao** [hazelcast/hazelcast-jetty-sessionmanager#15]
We are using Jetty 9.3.x with Hazelcast-Jetty-Sessionmanager for Jetty 9. I noticed metrics emitted by Hazelcast Session Manager is limited to the JVM and does not consider sessions available across cluster.

This behavior seems to be originating from `org.eclipse.jetty.nosql.NoSqlSessionManager` which is extending `org.eclipse.jetty.server.session.AbstractSessionManager`, this class has embedded logic to use `org.eclipse.jetty.util.statistic.CounterStatistic` and `org.eclipse.jetty.util.statistic.SampleStatistic`. These Statistics information models do provide support for cluster and are very JVM specific.

I believe Session Metrics exposed when using Hazelcast Jetty Session Manager should be cluster based than JVM based. In order to fix this behavior the above needs to change.

Let me know if contributions are welcome, will be happy to send a pull request across.

Version Details :-
Jetty - 9.3.x
JDK - 1.8.x
Hazelcast - 3.10.4
Hazelcast-Jetty-SessionManager - 1.0.2

Regards,
-Yogesh

**Comment by mesutcelik** [comment]
Hi @yogeshrao ,
Can you please open the issue on [Jetty Repository](https://github.com/eclipse/jetty.project/tree/jetty-9.3.x/jetty-hazelcast) and send potential contribution there?

The integraton has been moved to main jetty project and active development is in main jetty repository.

**Comment by yogeshrao** [comment]
Hello @mesutcelik 

I did look at Jetty repository especially Jetty-Hazelcast project for 9.3.x branch, based on the pom it has put in a dependency on `com.hazelcast:hazelcast-jetty9-sessionmanager:1.0.2`. The source has been rewritten as part of Jetty 9.4.x.

As suggested let me try opening the issue within Jetty Repo.

Thank you!

I am also closing this opened issue
