### ISSUE TITLE
Support for Jetty 9.4 - SessionDataStore

### ISSUE THREAD

**Issue by blop** [hazelcast/hazelcast-jetty-sessionmanager#4]
Session management has been refactored in Jetty 9.4.

https://www.eclipse.org/jetty/documentation/current/upgrading-jetty.html#_upgrading_from_jetty_9_3_x_to_jetty_9_4_0

https://www.eclipse.org/jetty/documentation/current/session-management.html#jetty-sessions-architecture

We need a HazelcastSessionDataStore implementation that'll replace HazelcastSessionManager and HazelcastSessionIdManager.

Maybe a HazelcastSessionCache with near-cache.

;-)

**Comment by mesutcelik** [comment]
+1

any contribution is very welcome!

**Comment by olamy** [comment]
see #8

**Comment by blop** [comment]
Available with jetty-hazelcast since version 9.4.7.v20170914
