### ISSUE TITLE
Possible memory leak in HazelcastSessionManager

### ISSUE THREAD

**Issue by jejohnsen** [hazelcast/hazelcast-jetty-sessionmanager#5]
I'm using hazelcast-jetty9-sessionmanager to handle session distribution. One of the requests is a special case where the request is performed at regular intervals without reusing sessions, and this causes the JVM to run out of heap space after a couple of weeks.

I've found that when `HazelcastSessionIdManager.cleanUp()` is called to remove old sessions, it only removes the sessions from the Hazelcast IMap `sessions`, and not from the local `_sessions` Map of `NoSqlSessionManager` (parent of `HazelcastSessionManager`). Is this a bug, or am I doing something wrong in my setup, which prevents proper cleanup?

A fix seems to be to make `HazelcastSessionIdManager.cleanUp()` call `HazelcastSessionManager.expire()` on each invalid session. I also added a remove to `sessionIds`. Let me know if you want me to create a pull request with this fix.

**Comment by mesutcelik** [comment]
a PR would be appreciated @jejohnsen 
Thx in advance!

**Comment by mesutcelik** [comment]
Hi @jejohnsen ,
Were you able to check 9.4.7.v20170914 and later version of Jetty? Hazelcast Session Replication is distributed by Jetty after the version above so please refer to the Jetty distribution.
see related comment https://github.com/hazelcast/hazelcast-jetty-sessionmanager/issues/4#issuecomment-332544340
